name: Sufrimiento

on:
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "http://192.168.1.194:80"

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: "https://www.zaproxy.org"
