name: Test site for publicly known js vulnerabilities

on:
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "http://localhost:80"
