on:
  schedule:
    # Runs every day At 01:00.
    #- cron:  '0 1 * * *'
    - cron:  '0,44 * * * *'

jobs:
  zap_scan:
    runs-on: windows-latest
    name: Scan Cyber III Site
    steps:
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
            
        with:
          target: 'http://localhost:80'
